= Plugin Development

How to develop a plugin.
Basics. Annotations?
Example project.

How to test plugins?

NOTE: Think about a good example here?

== Reasons

* Reasons to develop a plugin?
* Why is it better to write a plugin instead using scripts/external execution of Java/Groovy/Kotlin whatever code?

Often I see people developing maven plugins which are superfluous, cause the functionality is already
provided by one of the existing plugins or a combination of other plugins.

So the question is: When should I start to think about creating my own plugin?
The simple answer to this: If the needed functionality is not being provided by any existing plugin.


Example when to create a plugin?

== Basics
What is a Mojo?

* The annotations for plugins which are needed?
* How to build a plugin?
* How to test a plugin?

* How to create a very basic plugin

=== Building a plugin

* What is needed to build a plugin?
* How does a Maven project look like for building a plugin?

== Testing

Testing a plugin is one of the most challenging thing cause a plugin which is running inside a container (Maven Runtime)
has several aspects of testing.

In general there at least three different typs of tests you usually (should) write:

. The Java code (more or less independent) functionality you would like to put into a plugin.
** Usually covered by unit/integration tests which you (should) already know.
. The Mojo itself?
. The interaction with a real project?
** How does a plugin behave within a real project setup?



Testing frameworks / Support

* {link-maven-invoker-plugin}
* https://github.com/khmarbaise/maven-it-extension
* http://maven.apache.org/plugins/maven-invoker-plugin/index.html


https://github.com/asciidoctor/asciidoctor-maven-plugin

=== Compatibility

There a different aspect of compatibility. The first one is:

* Which minimum Java version you should support?
* Minimum Maven version you will require?