:sourcedir: examples/multi-modules

:web-application-archive: https://en.wikipedia.org/wiki/WAR_(file_format)
:enterprise-application-archive: https://en.wikipedia.org/wiki/EAR_(file_format)
:openapi-initiave: https://www.openapis.org/

= Multi Module Builds

Sometimes it is sufficient having a single pom file and a limited number of Java classes
which are combined into a single jar file.

This is a solution in a number of cases but not for all kind of project
types. In times of microservices projects becoming smaller even though
it happens that you would like to separate out parts. For example having a generation
of {openapi-initiave}[OpenAPI based code], or things like your jpa repositories (from
a Spring Boot app) etc.

If you think about creating a command line app including a web application where you
share code. That means you would have a command line part (module), a web application
part(module) and common code (module). This results in a nice multi-module-build.

In the JEE area where several parts of an enterprise applications make sense to
separate the creation of those kind of archive like
{enterprise-application-archive}[Enterprise Application Archive(ear)],
the {web-application-archive}[web application archive(war)] etc.

Nevertheless, a project can become larger, when you realize it would make it easier
to separate several parts out into a higher level of groupings.

In such cases it makes sense to create a multi-module-build. So start with a
look on the basic structure of a multi-module-build.

== Basic Structure

Lets us take the example from the link:#_multi_module_builds[Overview] chapter about the
command line app. We could name those modules like this:

* module-cli
* module-web
* module-common

//TODO: Maybe I need to reconsider this?
// In a single project structure you might have use to structure it by using package names,
// but technically you would have run into several issues because in Apache Maven its basic
// idea is having a single project will produce a single artifact like jar, ear, war or alike.
// By using some tricky things you would have achieved to generate different artifacts from a single
// project but that would have resulted into a lot configuration etc.
//TODO: Try to make such set as an example!!! (Bad Example!)

=== Directory Structure

Based on this assumption a directory structure could look like this. We assume further that the `root`
directory is the name of the git repository which will be created:
[source]
----
root
 +-- module-cli
 +-- module-common
 +-- module-web
----

//FIXME: Maybe we should those hints in later chapters...
// This kind of approach has a number of advantages, because you have all the
// code in a single location. This setup will make it possible to make some
// refactoring over different modules via your IDE etc.

Now let us dive into the details about such a project structure. What
needs to be done to create such structure (apart from creating
the directories). How could we build such a project and what kind of consequence
are following from it.

Based on the idea of the relationship of the modules it is useful to create
an appropriate directory structure.

[source]
---------------
 +--- pom.xml
   +--- module-cli
   +--- module-web
   +--- module-common
---------------

=== The Multi-Module-Parent

There are some parts which you need to pay attention to, to get a good working
experience. The first thing is the `pom.xml` file on the root level of this structure.
This is usually called the "parent" or multi-module-parent. This looks very similar like this:

[source,xml]
.pom.xml
----
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  ...

  <groupId>com.soebes.mpg.examples.mmb</groupId>
  <artifactId>parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  ..
  <modules>
    <module>module-cli</module>
    <module>module-common</module>
    <module>module-web</module>
  </modules>
  ..
</project>
----
This `pom.xml` file contains the usual parts like groupId, artifactId, version but at least
one very important difference to other project which is the `<packaging>pom</packaging>`.
And of course the module defined by the usage of the `<modules>..</modules>` tag including the
list of module which are defined by `<module>...</module>`. The names like `module-cli` etc.
correspond to the directories on the file system.

//TODO: Hint not necessary but useful? Write about other options?
[source]
---------------
 +--- pom.xml
   +--- module-cli
   +--- module-web
   +--- module-common
---------------

In a usual Maven project you have a single `pom.xml` file, and then you start with
the `src/` directory where your code lives. The directory is often enriched with
other files like a `README.md` (or alike) etc.

The `README.md`(or alike) of course are often being found in multi-module-build as well.


This pom file contains no code nor does it produce an artifact as the usual
maven project. This means in other words it does not produce an `jar`-File.
This is the reason why this Maven project defines it's packaging as `pom`.

But on the level of the parent `pom.xml` you will not find any `src` directory.





Apart from the above you need to define the list of modules which you
would like include in this parent. It is best practice to name the
folders as their appropriate `artifactId`. So now let us take a look
at a module how its pom file looks like:


[source,xml]
.pom.xml
----
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.soebes.mpg.examples.mmb</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>module-core</artifactId>
...
</project>
----


http://stackoverflow.com/questions/11528877/releasing-a-multi-module-maven-project-hosted-in-single-git-repository/[See here]


What is the basic idea of a multi module build? Same version? Same time of releasing them.

Reasons to create a multi module setup:


- Multiple Modules
  - [.line-through]#mvn install (first why?)#
  - Unit Tests (mvn test)
  - Integration Test (mvn integration-test)
  - packaging
  - use of an module from a reactor build in other projects?
  - Release all modules/projects at one point in time
  - All the modules are related to each other ?


Pro's and Cons'
http://stackoverflow.com/questions/23584429/releasing-a-modular-maven-project

Jenkins support for separated maven projects to be released:
https://wiki.jenkins-ci.org/display/JENKINS/Maven+Cascade+Release+Plugin


Aggregator ? Difference.

http://stackoverflow.com/questions/23936339/maven-parent-project-structure


What if only a single modules code has been changed? Can i release only a single
module from the multi module build? Draw backs?


== Releasing a Multi module Project

From root, single module?
?


=== Examples

==== XXX


== Spring Boot

A multi module project based on Spring Boot.

spring boot project setup.

[source]
---------------
root
 +--- pom.xml
   +--- jpa
   +--- controllers
   +--- application
---------------

